spring:
  application:
    name: spotifycatalog
  profiles:
    default: ingest
    group:
      ingest-run: [ ingest, flyway ]

  r2dbc:
    url: r2dbc:mysql://localhost:3306/spotifycatalog
    username: root
    password: root1234

  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
