spring:
  config:
    activate:
      on-profile: flyway

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false

  datasource:
    url: jdbc:mysql://localhost:3306/spotifycatalog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.flywaydb: INFO
