spring:
  flyway:
    enabled: true
  r2dbc:
    url: r2dbc:mysql://mysql:3306/spotifycatalog
    username: app
    password: app

  datasource:
    url: jdbc:mysql://mysql:3306/spotifycatalog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true
    username: app
    password: app
    driver-class-name: com.mysql.cj.jdbc.Driver


