spring:
  r2dbc:
    url: r2dbc:mysql://mysql:3306/spotifycatalog
    username: app
    password: app

  flyway:
    enabled: true
    url: jdbc:mysql://mysql:3306/spotifycatalog
    user: app
    password: app

  sql:
    init:
      mode: never

server:
  port: 8080
