services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: spotifycatalog
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papp"]
      interval: 5s
      retries: 20

  spring:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: spotifycatalog-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
